name: calculator_task

on:
  workflow_dispatch: 
    inputs:
      first:
        type: string
        description: Enter first number

      second:
        type: string
        description: Enter second number

      operator:
        type: choice
        description: Enter the operator
        options:
        - ADD
        - Subs
        - Mult
        - Div
    
jobs:
  calculator:
    runs-on: ubuntu-latest

    steps:
    - name: Calculator
      run: echo "${{ github.event.inputs.first }}
        
