name: calculator_task

on:
  workflow_dispatch: 
    inputs:
      first:
        type: string
        description: Enter first number

      second:
        type: string
        description: Enter second number

      operator:
        type: choice
        description: Enter the operator
        options:
        - '+'
        - '-'
        - '*'
        - '/'

#jobs:
  #calculator:
    #runs-on: ubuntu-latest

    #steps:
    #- name: Calculator
     # run: echo "${{ github.event.inputs.first }}"

        
jobs:
  calculator:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Calculator
      if: ${{ github.event.inputs.operator }}=='+'
      run: sh ./add.sh
      env:
        first_val:  ${{ github.event.inputs.first }}
