name: calculator_task

on:
  workflow_dispatch: 
    inputs:
      first:
        type: string
        description: Enter first number

      second:
        type: string
        description: Enter second number

      operator:
        type: choice
        description: Choose the operator
        options:
        - "+"
        - "-"
        - "*"
        - "/"

#jobs:
  #calculator:
    #runs-on: ubuntu-latest

    #steps:
    #- name: Calculator
     # run: echo "${{ github.event.inputs.first }}"

        
jobs:
  inputs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: First Input
      run: echo "First input is ${{guthub.event.inputs.first}}"
    - name: Second Input
      run: echo "Second input is ${{guthub.event.inputs.first}}"
    - name: Operator Input
      run: echo "First input is ${{guthub.event.inputs.first}}"
  output:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Calculator  
      run: sh ./calculator.sh
      env:
        first_val:  ${{ github.event.inputs.first }}
        second_val: ${{ github.event.inputs.second }}
        operator_val: ${{ github.event.inputs.operator }}
