name: calculator_task

on:
  workflow-dispatch: 
    inputs:
      first:
        type: string
        description: Enter first number

      second:
        type: string
        description: Enter second number

      operator:
        type: choose
        description: Enter the operator
        options:
        - ADD
        - Subs
        - Mul
        - Div
    
jobs:
  calculator:
    runs-on: ubuntu-latest

    steps:
    - name: Calculator
      run: echo "${{ github.event.inputs.first }} ${{ github.event.inputs.second }} ${{ github.event.inputs.operator }}"

        
