name: calculator_task

on:
  workflow_dispatch: 
    inputs:
      first:
        type: string
        description: Enter first number

      second:
        type: string
        description: Enter second number

      operator:
        type: choice
        description: Enter the operator
        options:
        - '+'
        - '-'
        - '*'
        - '/'

#jobs:
  #calculator:
    #runs-on: ubuntu-latest

    #steps:
    #- name: Calculator
     # run: echo "${{ github.event.inputs.first }}"

        
jobs:
  calculator:
    runs-on: ubuntu-latest

    steps:
    - name: Calculator
      if: ${{ github.event.inputs.operator }}=='+'
      env:
        run: |
          echo ::set-env name={first_value}::{${{ github.event.inputs.first }}}
          echo ::set-env name={second_value}::{${{ github.event.inputs.second }}}
          echo ::set-env name={result}::{${{ $first_value + $second_value }}}
        - run: echo $result
