name: calculator_task

on:
  workflow_dispatch: 
    inputs:
      first:
        type: string
        description: Enter first number

      second:
        type: string
        description: Enter second number

      operator:
        type: choice
        description: Enter the operator
        options:
        - '+'
        - '-'
        - '*'
        - '/'

#jobs:
  #calculator:
    #runs-on: ubuntu-latest

    #steps:
    #- name: Calculator
     # run: echo "${{ github.event.inputs.first }}"

        
jobs:

  Addition:
    if: ${{ github.event.inputs.operator }}=='+'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Addition  
      run: sh ./add.sh
      env:
        first_val:  ${{ github.event.inputs.first }}
        second_val: ${{ github.event.inputs.second }}

  Substraction:
    if: ${{ github.event.inputs.operator }}=='-'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Susbtraction
      run: sh ./substract.sh
      env:
        first_val:  ${{ github.event.inputs.first }}
        second_val: ${{ github.event.inputs.second }}
  
  Multiplication:
    if: ${{ github.event.inputs.operator }}=='*'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Multiplication
      run: sh ./multiplication.sh
      env:
        first_val:  ${{ github.event.inputs.first }}
        second_val: ${{ github.event.inputs.second }}

  Division:
    if: ${{ github.event.inputs.operator }}=='/'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Division
      run: sh ./division.sh
    env:
      first_val:  ${{ github.event.inputs.first }}
      second_val: ${{ github.event.inputs.second }}
