name: calculator_task

on:
  workflow_dispatch: 
    inputs:
      first:
        type: string
        description: Enter first number

      second:
        type: string
        description: Enter second number

      operator:
        type: choice
        description: Enter the operator
        options:
        - '+'
        - '-'
        - '*'
        - '/'

#jobs:
  #calculator:
    #runs-on: ubuntu-latest

    #steps:
    #- name: Calculator
     # run: echo "${{ github.event.inputs.first }}"

        
jobs:
  calculator:
    runs-on: ubuntu-latest

    steps:
    - name: Calculator
      if: ${{ github.event.inputs.operator }}=='+'
      env: 
        result: $ {{ github.event.inputs.first }}
      run: |
        echo ::set-env name=res::$((${{ github.event.inputs.first }} + ${{ github.event.inputs.second }}))
        - run: echo $res
